# --- This is the new section that links our reusable secret vault ---
envVarGroups:
  - name: taskmaster-secrets # This name MUST EXACTLY match the group you created in Render

services:
  # --- Service 1: Redis ---
  - name: redis
    type: redis
    plan: free
    ipAllowList: []

  # --- Service 2: Geo Service ---
  - name: geo-service
    type: web
    env: docker
    plan: free
    healthCheckPath: /
    dockerContext: ./services/geo-service
    dockerfilePath: ./services/geo-service/Dockerfile
    envVars:
      - key: PORT # This is not a secret, so it stays here
        value: 10000
      # All secrets are now inherited from the envVarGroup

  # --- Service 3: Real-time Service ---
  - name: realtime-service
    type: web
    env: docker
    plan: free
    healthCheckPath: /
    dockerContext: ./services/realtime-service
    dockerfilePath: ./services/realtime-service/Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  # --- Service 4: Auth Service ---
  - name: auth-service
    type: web
    env: docker
    plan: free
    healthCheckPath: /
    dockerContext: ./services/auth-service
    dockerfilePath: ./services/auth-service/Dockerfile
    envVars:
      - key: PORT
        value: 10000
      # All secrets are now inherited from the envVarGroup

  # --- Service 5: Task Service ---
  - name: task-service
    type: web
    env: docker
    plan: free
    healthCheckPath: /
    dockerContext: ./services/task-service
    dockerfilePath: ./services/task-service/Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      # All secrets are now inherited from the envVarGroup

  # --- Service 6: Next.js Client ---
  - name: client
    type: web
    env: docker
    plan: free
    healthCheckPath: /
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    # The 'envVars' for the client are for building URLs, not secrets, so they stay here.
    envVars:
      - key: NEXT_PUBLIC_AUTH_API_URL
        fromService:
          type: web
          name: auth-service
          property: host
      - key: NEXT_PUBLIC_TASK_API_URL
        fromService:
          type: web
          name: task-service
          property: host
      - key: NEXT_PUBLIC_REALTIME_API_URL
        fromService:
          type: web
          name: realtime-service
          property: host
      # The Maps API key is also inherited from the envVarGroup
