services:
  # --- Service 1: The Redis Database ---
  - type: redis
    name: redis
    plan: free
    ipAllowList: []

  # --- Service 2: The Geo Service (Backend) ---
  - type: web
    name: geo-service
    env: docker
    dockerContext: ./services/geo-service
    dockerfilePath: ./services/geo-service/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: GOOGLE_GEOCODING_API_KEY
        fromSecret: GOOGLE_GEOCODING_API_KEY

  # --- Service 3: The Real-time Service (Backend) ---
  - type: web
    name: realtime-service
    env: docker
    dockerContext: ./services/realtime-service
    dockerfilePath: ./services/realtime-service/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - fromService: # Get Redis URL from the managed service
          type: redis
          name: redis
          property: url
        key: REDIS_URL

  # --- Service 4: The Auth Service (Backend) ---
  - type: web
    name: auth-service
    env: docker
    dockerContext: ./services/auth-service
    dockerfilePath: ./services/auth-service/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET

  # --- Service 5: The Task Service (Backend) ---
  - type: web
    name: task-service
    env: docker
    dockerContext: ./services/task-service
    dockerfilePath: ./services/task-service/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: GCS_PROJECT_ID
        fromSecret: GCS_PROJECT_ID
      - key: GCS_BUCKET_NAME
        fromSecret: GCS_BUCKET_NAME
      - key: GOOGLE_APPLICATION_CREDENTIALS
        fromSecret: GCP_CREDENTIALS_JSON
      - fromService:
          type: redis
          name: redis
          property: url
        key: REDIS_URL

  # --- Service 6: The Next.js Client (Frontend) ---
  - type: web
    name: client
    env: docker
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    plan: free
    healthCheckPath: /
    # The 'envVars' here are automatically available during the build process
    envVars:
      - key: NEXT_PUBLIC_AUTH_API_URL
        fromService:
          type: web
          name: auth-service
          property: url
      - key: NEXT_PUBLIC_TASK_API_URL
        fromService:
          type: web
          name: task-service
          property: url
      - key: NEXT_PUBLIC_REALTIME_API_URL
        fromService:
          type: web
          name: realtime-service
          property: url
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        fromSecret: GOOGLE_MAPS_API_KEY
